# Generated by Django 2.2.17 on 2020-11-25 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('first_lname', models.CharField(max_length=100)),
                ('second_lname', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('first_lname', models.CharField(max_length=100)),
                ('second_lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
                ('behavior', models.TextField()),
                ('age', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patitofeo.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('date', models.DateField()),
                ('pet', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='patitofeo.Pet')),
                ('profesional', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='patitofeo.Employee')),
            ],
        ),
    ]
